### ISSUE TITLE
Add initial commit

### ISSUE THREAD

**Issue by Shreyanand** [open-services-group/metrics#1]
Add initial commit with [template](https://github.com/aicoe-aiops/project-template) files to this repository. 
cc @hemajv

**Comment by Shreyanand** [comment]
@MichaelClifford @tumido It seems like I can't fork this repo since it is empty. Also, I don't have owner access and that means I can't add a file like suggested in this [thread](https://stackoverflow.com/questions/39013301/how-do-i-fork-an-empty-repository-on-github). Circle Circle :)

**Comment by hemajv** [comment]
assuming we need to add a new team and mention us as maintainers like so: https://github.com/open-services-group/community/blob/main/github-config.yaml#L107

**Comment by harshad16** [comment]
yes that is correct :)

**Comment by harshad16** [comment]
If @hemajv  you are going lead wth someone, add them as maintainers and people like me add us in members.

**Comment by Shreyanand** [comment]
![Screenshot from 2022-02-03 18-14-41](https://user-images.githubusercontent.com/8916126/152445226-8270f059-7965-4899-b2b4-c397dcba7281.png)

@harshad16 Am I doing something wrong here?

**Comment by harshad16** [comment]
I dont think so :( 
can share you `git remote -v` ?
also screenshot of what you see when you reach here: https://github.com/open-services-group/metrics

**Comment by MichaelClifford** [comment]
@harshad16 are there docs for setting up a new repo in this org?
@schwesig

**Comment by Shreyanand** [comment]
@harshad16 
Remote
![Screenshot from 2022-02-04 10-03-17](https://user-images.githubusercontent.com/8916126/152551881-cadcd8a5-d317-4e88-a2d6-1c89e23f510a.png)

Repo page
![Screenshot from 2022-02-04 10-01-04](https://user-images.githubusercontent.com/8916126/152552351-0564c969-16f6-4f54-a3ac-a267ea4ab101.png)

**Comment by harshad16** [comment]
> are there docs for setting up a new repo in this org? 

No idea :man-shrugging:
upstream docs are here: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/README.md

**Comment by harshad16** [comment]
The postsubmit job didnt run properly. the team isn't created.
https://github.com/orgs/open-services-group/teams

doing further testing and investigation.

**Comment by harshad16** [comment]
Going to revert the previous pr and create a new one 
https://github.com/open-services-group/community/pull/44
to trace through the issue.

**Comment by harshad16** [comment]
the solution doesnt work:
```
{"component":"unset","error":"status code 422 not one of [200], body: {\"message\":\"Validation Failed\",\"errors\":[{\"message\":\"The branch main was not found. Please push that ref first or create it via the Git Data API.\",\"resource\":\"Repository\",\"field\":\"default_branch\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/reference/repos#update-a-repository\"}","file":"prow/cmd/peribolos/main.go:1063","func":"main.configureRepos","level":"error","msg":"failed to update repository","repo":"devsecops","severity":"error","time":"2022-02-04T[19](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/logs/peribolos/1489689620797984768#1:build-log.txt%3A19):57:46Z"}
{"client":"github","component":"unset","file":"prow/github/client.go:891","func":"k8s.io/test-infra/prow/github.(*client).log","level":"info","msg":"GetRepo(open-services-group, metrics)","severity":"info","time":"[20](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/logs/peribolos/1489689620797984768#1:build-log.txt%3A20)22-02-04T19:57:46Z"}
{"component":"unset","file":"prow/cmd/peribolos/main.go:1052","func":"main.configureRepos","level":"info","msg":"repo exists, considering an update","repo":"metrics","severity":"info","time":"2022-02-04T19:57:46Z"}
{"component":"unset","file":"prow/cmd/peribolos/main.go:209","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure open-services-group repos: status code 422 not one of [200], body: {\"message\":\"Validation Failed\",\"errors\":[{\"message\":\"The branch main was not found. Please push that ref first or create it via the Git Data API.\",\"resource\":\"Repository\",\"field\":\"default_branch\",\"code\":\"invalid\"}],\"documentation_url\":\"https://docs.github.com/rest/reference/repos#update-a-repository\"}","severity":"fatal","time":"2022-02-04T19:57:46Z"}
```

cc: @goern , can you please take a look.

for now we should create the team manually.

**Comment by hemajv** [comment]
@harshad16 I created a team manually (https://github.com/orgs/open-services-group/teams/sp-metrics-leads), however I wasn't able to link a repo to it since it said I can only add repos to which I have admin access to

**Comment by harshad16** [comment]
Only org admin, can do this.
So we would need help from them.

**Comment by goern** [comment]
seeAlso https://github.com/open-services-group/community/pull/46

**Comment by goern** [comment]
so... I gonna write up some stuff in this PR, @schwesig has started some community janitoring docs...

0. I'd prefer to keep all the reviewer/approver role declarations in an OWNERS file rather than proxy'ing it to a GitHub group. 
1. make sure the subproject is linked/references from a SIG, see https://github.com/open-services-group/community/blob/main/sigs.yaml#L44-L51 for an example
2. the actual project/repo creation happens via https://github.com/open-services-group/community/blob/main/sigs.yaml#L44-L51 which was added by https://github.com/open-services-group/community/commit/6e3119c3690ee6171f693f37a05ac88095ae5d83
3. please make sure, that the SourceOps team has admin access to the repo, see https://github.com/open-services-group/community/blob/main/github-config.yaml#L104-L106

I'll remove https://github.com/orgs/open-services-group/teams/sp-metrics-leads now, and check for the peribolois/label jobs on this org.

**Comment by hemajv** [comment]
We mainly included the metrics-lead team as we were unable to create initial commits to the repo after it was created, so the creation of main branch/OWNERS file sounds good to me.

**Comment by goern** [comment]
If we go ahead with the pattern, shall we create a `metrics-maintainers` GitHub Team, that is able to admin the metrics repo (what would include push to main branch? But also agree on not using GitHub teams within OWNERS file to keep clarity?

https://github.com/open-services-group/community/pull/46

**Comment by Shreyanand** [comment]
> If we go ahead with the pattern, shall we create a `metrics-maintainers` GitHub Team, that is able to admin the metrics repo (what would include push to main branch? But also agree on not using GitHub teams within OWNERS file to keep clarity?
> 
> [open-services-group/community#46](https://github.com/open-services-group/community/pull/46)

That sounds good. So for each subproject or wg in this org, there would be one Github Team that gives admin access to the repo. And, the OWNERS in each repo, that doesn't reference the GH team, helps PROW to decide approvers and reviewers, right?

**Comment by goern** [comment]
sounds good to me

@tumido @harshad16 @HumairAK

**Comment by goern** [comment]
> That sounds good. So for each subproject or wg in this org, there would be one corresponding Github Team that gives admin access to the repo.

and I'd call this 'the maintainers' of the project/repo (on GitHub, via github-config.yaml), and we will have the approvers/reviewers (via OWNERS), and SourceOps team as a super-admin on all repos of the org (via github-config.yaml)

**Comment by Shreyanand** [comment]
> and I'd call this 'the maintainers' of the project/repo (on GitHub, via github-config.yaml)

To confirm, the root cause of why the GH team was not formed when we updated the github-config.yaml for this repository is that we didn't add the sub-project first like in this [example](https://github.com/open-services-group/community/blob/main/sigs.yaml#L44-L51)?

**Comment by Shreyanand** [comment]
Initial [commit added](https://github.com/Shreyanand/metrics/commit/fbd53df11649ca0637a89774398b7a4161c66376)
