### ISSUE TITLE
Spike: Define OKR completion

### ISSUE THREAD

**Issue by Shreyanand** [open-services-group/metrics#10]
This issue is created to discuss different approaches that we can take to reflect meaningful progress of a key objective. 
The comments in this thread can be designs to solve this problem. We can discuss alternative approaches and once we start converging, we can add missing details.

Example solution:

1. Track each OKR in one parent issue
2. Create major EPICs in the OKR issue 
3. Add smaller issues for each EPIC
4. Fetch data for all these issues and come up with a score that maps to % finished. 

cc @hemajv

**Comment by MichaelClifford** [comment]
:+1: @Shreyanand yes, I think having OKR issues to track is a good approach to quantify OKR progress. : )

Is there a need to create an OKR label that we can use?

**Comment by Shreyanand** [comment]
Yes I think an OKR label would make our lives easier. @hemajv did you use labels in your initial experiments or some other approach?

**Comment by hemajv** [comment]
@Shreyanand so the labels we had were mainly to differentiate which teams the OKR belongs to

**Comment by Shreyanand** [comment]
@durandom pitched that we start without the label "OKR" so that we are not imposing a structure on the repositories. Our first try should be to see If we can measure the progress of a repository based on the quantity and quality of issues and PRs being created. If that doesn't work or in other words if it doesn't effectively reflect the progress of a repository, we can think of imposing a structure in place as a last resort.

**Comment by hemajv** [comment]
As various KRs for objectives focus on metrics, it would be a good time to start defining the process around how a team would approach for having metrics in place for their use case. The process would cater to having feature requests created via
issues in this repo highlighting:

- The targeted objective
- The metrics the team would like to have
- Final output to showcase the metrics (i.e. report, dashboard, notebook etc)
