### ISSUE TITLE
Collect metrics for all sub-projects in the OSG org

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#13]
Collect GitHub data using MI scheduler i.e issues/PR data for the sub projects in the OSG org mentioned in https://github.com/open-services-group/community/blob/main/sigs.yaml

(Related to #5)

**Comment by oindrillac** [comment]
@hemajv we can use the MI tool to download repositories pull request data using the `srcopsmetrics` [PyPi package](https://pypi.org/project/srcopsmetrics/). Getting issues is currently blocked by https://github.com/thoth-station/mi/issues/504

For example:
`python -m srcopsmetrics.cli --create-knowledge --is-local --repository open-services-group/community --entities PullRequest`

If we want to store them remotely and configure the scheduled upload of the data, do we know where we want to store them? Do we have a bucket for such data? Perhaps, we can use the [OPF Public bucket](https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md) for this?

**Comment by hemajv** [comment]
> @hemajv we can use the MI tool to download repositories pull request data using the `srcopsmetrics` [PyPi package](https://pypi.org/project/srcopsmetrics/). Getting issues is currently blocked by [thoth-station/mi#504](https://github.com/thoth-station/mi/issues/504)
> 
> For example: `python -m srcopsmetrics.cli --create-knowledge --is-local --repository open-services-group/community --entities PullRequest`
> 
> If we want to store them remotely and configure the scheduled upload of the data, do we know where we want to store them? Do we have a bucket for such data? Perhaps, we can use the [OPF Public bucket](https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md) for this?

Yes, I think we can try using the MI tool directly and the opf public bucket sounds good to me :+1:

**Comment by oindrillac** [comment]
We were able to successfully fetch the **Pull Requests** and **Issues** data for repos under the the OSG org, mentioned in [sigs.yaml](https://github.com/open-services-group/community/blob/main/sigs.yaml) using the [MI tool](https://github.com/thoth-station/mi).

The Github repo data is now stored in the [OPF Public Bucket](https://github.com/operate-first/apps/blob/master/docs/content/odh/trino/access_public_bucket.md).

All the data is stored under the following prefix : 

`s3://opf-datacatalog/open-services-group/metrics/github/srcopsmetrics/bot_knowledge/org-name/repo-name/PullRequest.json`

for eg : `opf-datacatalog/open-services-group/metrics/github/srcopsmetrics/bot_knowledge/aicoe-aiops/operate-first-data-science-community/PullRequest.json`

**Comment by MichaelClifford** [comment]
@hemajv Isn't this issue dependent on the issue in MI scheduler being closed? https://github.com/thoth-station/mi/issues/530

**Comment by hemajv** [comment]
@MichaelClifford so I figured that issue can still be open for helping us to schedule and automate the data collection phase as part of our pipeline. But for our initial work of analyzing the metrics, we have sufficient data and hence thought of closing this issue out. Happy to keep it open as well
