### ISSUE TITLE
Superset dashboard to visualize metrics

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#21]
Implement a Superset dashboard to visualize the metrics derived for the different repositories and org.

**Acceptance Criteria**

- [x] Dashboard displays initial set of metrics calculated for repo/org (those defined in: https://github.com/open-services-group/metrics/issues/3)
- [x] Dashboard should be filterable to show metrics at an repo/org level
- [x] Dashboard should categorize and display the metrics on a SIG level i.e have charts with metrics grouped by each SIG

**Comment by Shreyanand** [comment]
Tasks
Write queries for:

- [ ] Number of issues/PR in a timeframe (sum based on time filter)
- [ ] Replicate it for open and closed issues
- [ ] Ratio of open to close issues (group by time frame and then sum of open/ sum of close)
- [ ] Mean time to close
- [ ] Create dashboard markdowns and row, column splits

**Comment by hemajv** [comment]
Initial dashboard created here: https://superset.operate-first.cloud/superset/dashboard/11/

**Comment by hemajv** [comment]
Looks like there are some ongoing issues with Trino/Superset: https://github.com/operate-first/support/issues/541 due to which the dashboard isn't rendering

**Comment by hemajv** [comment]
Superset issues resolved and dashboard is functioning :+1:
