### ISSUE TITLE
Create contributors data frame for metrics

### ISSUE THREAD

**Issue by Shreyanand** [open-services-group/metrics#22]
For metrics related to contributors, we'd have create a table that Superset dashboard can use for calculation.

Acceptance

- [x] Update the kpi preprocessing notebook to add contributors table
- [x] Have columns: contributor_id, contributor_name, issues_created, PR_created, PR_reviewed,  PRs_authored, internal (bool), member_of_sig, member_of_subproject

**Comment by chauhankaranraj** [comment]
> * Have columns: contributor_id, contributor_name, issues_created, PR_created, PR_reviewed, internal (bool), member_of_sig, member_of_subproject

suggestion: since we often pair-program in PRs, should we add a "PRs_authored" column as well, to more accurately reflect contributions?
