### ISSUE TITLE
Add sigs information to data tables

### ISSUE THREAD

**Issue by Shreyanand** [open-services-group/metrics#23]
For grouping performance metrics based on special interest groups (SIGs), we have to add a column to the existing data tables with sig information it belongs to. The sig information should be parsed automatically from github.

Acceptance

- [x] Dataset for Superset graphs have a sigs column

**Comment by Shreyanand** [comment]
To add sigs information automatically, we'd have to update the yaml file elaborated in this [issue](https://github.com/open-services-group/community/issues/92).

**Comment by hemajv** [comment]
@Shreyanand can we close this issue out for now?

**Comment by Shreyanand** [comment]
We do have the sig column in the dataset but we still have to parse it automatically from some file on github. Let's close this when that's available, wdyt?

**Comment by hemajv** [comment]
okay sure :+1:
