### ISSUE TITLE
Do we want metrics for an earlier state of the repositories?

### ISSUE THREAD

**Issue by Shreyanand** [open-services-group/metrics#24]
In the current metrics dashboard, all the "Big number" graphs or in other words, graphs with just numbers, reflect the current state of the repository. These include number of open issues, number of closed issues, Mean Time to Close, and Ratio of open/close issues. 

If we want to get this information for an earlier state of the repository or if we want a time series of these metrics, we'd have to add more tables since Superset may not be able to calculate this. For example, if we want to see how Mean Time to close issue evolved over time for a repository we'd have to add a time series table for it. It can be useful if we are interested in seeing how the performance, engagement evolves in an open source repository. 

As a part of this issue, let's discuss if we need these metrics and if so, what's the  best way to implement them.

**Comment by schwesig** [comment]
For the first version, one number is fine, no time line/series is needed
 a) as long as we can set the time frame and change it manually for the numbers (right now we have this)
 b) first version means the main 2 to 4 indicators for Metrics Strategic for Q1 2022

For future versions, series are essential, to see the development.
So the current development should not block this.
BUT, we should not spend time (yet) on the series idea, until we have the 2 to 4 running indicators as our MVP.

**Comment by codificat** [comment]
/sig community-experience
to clarify the question from a "metrics strategic" POV
