### ISSUE TITLE
Q1 OKR dashboard

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#29]
We would like to have a separate Q1 OKR superset dashboard that displays the percentage of work completed/progress made on a given [objective defined for Q1](https://docs.google.com/document/d/1TeUwhWOh395GQG4MSgl-vU_LSh9eSw3RdCiTlaB5jqw/edit?usp=sharing).

**Acceptance Criteria**

The Superset dashboard should have charts for the following objectives:
- [x] **Objective 1: Establish team governance**
      - A chart displaying the percentage of people in the OSG team having at least 1 contribution in a given SIG/WG/project
- [x] **Objective 2: BYON for ODH**

**Comment by oindrillac** [comment]
> @oindrillac @pacospace can you help us understand what you consider "done" for the BYON objective for Q1 so that we can calculate this metric accordingly? We currently have issues/PRs data collected for the BYON repo and want to know if this data can help define the percentage of objective completed this quarter

@hemajv compiled a list of artifacts (issues, mockups, PRs etc) for the BYON WG, and categorized them under the targets that we have for this WG [here](https://docs.google.com/document/d/1j7VKbWDaS78SujwGpnpXUhfBOLzYPdvO9eeFAr_lHYU/edit?usp=sharing). Hope this helps with the dashboard. Let me know if there is anything that I can offer clarity on.

**Comment by hemajv** [comment]
Thanks @oindrillac we will try to capture these into the dashboard!

**Comment by aakankshaduggal** [comment]
Initial dashboard created here: https://superset.operate-first.cloud/superset/dashboard/13/

**Comment by oindrillac** [comment]
@aakankshaduggal @hemajv thanks for the dashboard. 💯  Can we include some metrics on external contributors? Since this is a cross org WG, maybe we can show some metrics on folks contributing from outside of OSG?

**Comment by hemajv** [comment]
@oindrillac we have included this now, thanks for the suggestion :+1:
