### ISSUE TITLE
Spike: Define initial set of metrics

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#3]
We should come up with a list of metrics we would like to start monitoring

**Comment by MichaelClifford** [comment]
Here are some metrics we can look at to get the conversation started: 

- [ ] number of open issues across all OSG org repos
- [ ] percent of issues open/closed  with the tag `OKR`
- [ ] number of open issues across all OSG org repos without assignees.
- [ ] number of open PR's across all OSG org repos
- [ ] Ratio of opened to closed PR's over the last 90 days (quarter) across all OSG org repos
- [ ] number of contributors across all OSG org repos


Each of these metrics is defined as "across all OSG org repos" assuming we will also be able to filter down to SIG, subproject or WG trivially.

**Comment by hemajv** [comment]
We have also started a doc to track all the metrics: https://docs.google.com/document/d/1uhF45-hOEBjg_f8HlXbqhNYfTzvUh-HgtNDEgc-mzgo/edit?usp=sharing
