### ISSUE TITLE
Spike: Select and prioritize Github repos and orgs we are interested in monitoring

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#4]
The aim of this issue is to select Github repositories and Orgs we want to track

Questions to answer:

1. Which repository and org can be used as an example for setting up the metric processing pipeline?
2. Assuming the pipeline is set, which repositories and Orgs should we replicate the process for?

**Comment by MichaelClifford** [comment]
/assign @schwesig 

@hemajv can you add some more detail to this issue? What is meant by `community entities` ? Is this anything other than our repos?

**Comment by schwesig** [comment]
If I understand it right, here my 5cents.
I think, widening the metrics to out-of-OSG communities can be nice, and we should not limit the general architecture to just OSG, but for our first MVP in Q1 we should focus on OSG repos.

**Comment by Shreyanand** [comment]
@MichaelClifford added some description and removed the ambiguous term `community entities` from the issue.

@schwesig Opening up to other communities seems like a great idea. We can focus on repos by our team in this issue and include other communities in separate issues possibly in subsequent quarters.

Based on our last meeting, it seems [BYON](https://github.com/open-services-group/byon) repo and the OSG org can be used as a first example. Then we can move on to repos and orgs for data science SIG, community experience SIG, and services SIG or in other words, all the repos and orgs in [sigs.yaml](https://github.com/open-services-group/community/blob/main/sigs.yaml)
@schwesig and @MichaelClifford if that seems like a good step forward, we can close this issue as both the questions are answered. If you have other ideas about what should be the first example or you think some repos outside the sigs.yaml need to be immediately tracked, we can discuss that here.

**Comment by hemajv** [comment]
@Shreyanand yes I agree :+1: For Q1, we can focus on implementing the pipeline taking the BYON repo as an example.

@schwesig Once we have a well defined pipeline, we can start extending and reusing it for other orgs/repos and create separate issues to track them.

**Comment by Shreyanand** [comment]
@schwesig That's a good question. BYON would be repo 1 or the repo that we use to build the pipeline. Then we can replicate it for other repos in the org [Open Services Group](https://github.com/open-services-group), i.e., metrics, community, and devsecops. So, the OSG org would be the first example of org wide metrics tracking. The reason for mentioning an org separate from a repo is that in our calculation of metrics, we can aggregate and report metrics for the complete org and answers questions like how many OKRs is this org targeting? What %of them were completely achieved? and so on. All of this should be in scope for Q1.
Thats per my understanding, I could be missing something here.

**Comment by MichaelClifford** [comment]
+1 to all of the above,
But I want to clarify, it is fine to start with BYON notebooks and OSG org, but to achieve our OKR goal, we need to be pulling data and providing metrics for all the repositories mentioned in the sigs.yaml. This extends beyond the OSG org.

I would prioritize getting fewer metrics (1 or 2) from all the repo's as opposed to a complete set of metrics from 1 or 2 repos right now.

**Comment by hemajv** [comment]
Yes agreed! We can start collecting data for all the repos mentioned in sigs.yaml and then start looking into the different metrics mentioned in https://github.com/open-services-group/metrics/issues/3

**Comment by Shreyanand** [comment]
To conclude the spike, we are focusing on metrics from the [OSG](https://github.com/open-services-group) org, and the repositories in the org mentioned in [sigs.yaml](https://github.com/open-services-group/community/blob/main/sigs.yaml) for the first iteration. Once we have the pipeline in place, we can replicate it for the Operate First and OS Climate Orgs and their repositories.
