### ISSUE TITLE
Tracking issue project board and assignees for an Issue

### ISSUE THREAD

**Issue by suppathak** [open-services-group/metrics#43]
An [issue](https://github.com/thoth-station/mi/issues/589) was created to upgrade [MI tool](https://github.com/thoth-station/mi) so that we can track features like linked project board, assignees for corresponding issue. Once this issue is merged we can update this [notebook](https://github.com/open-services-group/metrics/blob/main/notebooks/thoth_support_github_data.ipynb) to track the related metrics from [thoth-station/support](https://github.com/thoth-station/support) repo.

**Comment by schwesig** [comment]
/close
cleanup after change of orga
