### ISSUE TITLE
[EPIC] Metric collection

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#5]
- Identify relevant repos to fetch metrics
- Split metric collection from different sources into different issues
- Store metrics (via MI scheduler, Ceph)

**Comment by MichaelClifford** [comment]
> Identify relevant repos to fetch metrics

Please see https://github.com/open-services-group/community/blob/main/sigs.yaml which contains a list of all the repo's currently associated with the OSG org.

Here is an example: https://github.com/open-services-group/community/blob/245511c0abeca780747c903a1368a54091a5dd22/sigs.yaml#L44-L51

**Comment by MichaelClifford** [comment]
> Store metrics (via Augur, Ceph)

Is this still the approach? I thought we had discussed using the MI scheduler?

**Comment by oindrillac** [comment]
For reference: As part of AI4CI, we used Github PR data from the openshift/origin repository obtained using the [MI tool](https://github.com/thoth-station/mi) and we visualized the statistics, KPIs, metrics such as contributors over time, merge statistics over time, etc. on this SuperSet [dashboard](https://superset.operate-first.cloud/superset/dashboard/9/).

We also had plans on analyzing the Issues data, which is currently being discussed [here](https://github.com/thoth-station/mi/issues/504)
