### ISSUE TITLE
Project workflow diagram

### ISSUE THREAD

**Issue by hemajv** [open-services-group/metrics#9]
Create an architecture diagram describing the project workflow and implementation

**Comment by oindrillac** [comment]
Hi @hemajv @Shreyanand I started working on a very high level architecture diagram for this here: https://lucid.app/lucidspark/f7342083-d1ee-47e8-ac73-ff86862d65d2/edit?invitationId=inv_5a0b9d8b-fa06-49fc-8f38-5c78e9835faf

Happy to collaborate on this and come up with something nicer.

**Comment by hemajv** [comment]
> @hemajv Looks awesome!
> 
> Does adding this diagram to the README close the issue?

yes! If it looks good we can add it to the repo :+1:
